### ISSUE TITLE
ECB Decrypter is missing

### ISSUE THREAD

**Issue by igormoochnick** [mattn/lastpass-go#1]
Hi.  I'm trying your module but it fails to find ecb folder with the code for NewECBDecrypter.
Just curious if you forgot to commit it?

  Thank you

**Comment by mattn** [comment]
Maybe forgot to commit. I'll push in tomorrow. Thanks.

**Comment by mattn** [comment]
https://github.com/mattn/lastpass-go/commit/82bef8502f75dced582606e4c1099ba3492ee2d9
